sulu_tag:
    resource: "@SuluTagBundle/Resources/config/routing.yml"
    prefix:   /admin/tag

sulu_tag_api:
    resource: "@SuluTagBundle/Resources/config/routing_api.yml"
    prefix:   /admin/api

sulu_admin:
    resource: "@SuluAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sulu_contact:
    resource: "@SuluContactBundle/Resources/config/routing.yml"
    prefix: /admin/contact

sulu_contact_api:
    type: rest
    resource: "@SuluContactBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_security:
    resource: "@SuluSecurityBundle/Resources/config/routing.xml"
    prefix: /admin/security

sulu_security_api:
    type: rest
    resource: "@SuluSecurityBundle/Resources/config/routing_api.xml"
    prefix: /admin/api

sulu_content:
    resource: "@SuluContentBundle/Resources/config/routing.yml"
    prefix: /admin/content

sulu_content_api:
    type: rest
    resource: "@SuluContentBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing.yml"
    prefix: /admin/media

sulu_media_website:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"

sulu_media_api:
    resource: "@SuluMediaBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_category:
    resource: "@SuluCategoryBundle/Resources/config/routing.yml"
    prefix: /admin/category

sulu_category_api:
    resource: "@SuluCategoryBundle/Resources/config/routing_api.yml"
    prefix: /admin/api

sulu_snippet_api:
    resource: "@SuluSnippetBundle/Resources/config/routing_api.yml"
    type: rest
    prefix: /admin/api

sulu_location:
    resource: "@SuluLocationBundle/Resources/config/routing.yml"
    prefix: /admin/location

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing.yml"
    prefix: /admin/website

sulu_websocket:
    type: rest
    resource: "@SuluWebsocketBundle/Resources/config/routing.yml"
    prefix: /admin/websocket

sulu_core:
    type: rest
    resource: "@SuluCoreBundle/Resources/config/routing_api.xml"
    prefix: /admin/api

sulu_activity_api:
    type: rest
    resource: "@SuluActivityBundle/Resources/config/routing_api.xml"
    prefix: /admin/api

sulu_activity:
    resource: "@SuluActivityBundle/Resources/config/routing.xml"
    prefix: /admin/activity

sulu_contact_extension_api:
    resource: "@SuluContactExtensionBundle/Resources/config/routing.xml"
    prefix: /admin/contact

sulu_contact_extension:
    type: rest
    resource: "@SuluContactExtensionBundle/Resources/config/routing_api.xml"
    prefix: /admin/api

# for preview
client_website:
    type: portal
    resource: "@ClientWebsiteBundle/Resources/config/routing.yml"

sulu_translate:
    resource: "@SuluTranslateBundle/Resources/config/routing.yml"
    prefix: /admin/translate

sulu_translate_api:
    resource: "@SuluTranslateBundle/Resources/config/routing_api.yml"
    type: rest
    prefix: /admin/api

sulu_product:
    resource: "@SuluProductBundle/Resources/config/routing.yml"
    prefix: /admin/product

sulu_product_api:
    resource: "@SuluProductBundle/Resources/config/routing_api.yml"
    type: rest
    prefix: /admin/api

sulu_sales_order:
    resource: "@SuluSalesOrderBundle/Resources/config/routing.xml"
    prefix: /admin/order

sulu_sales_order_api:
    type: rest
    resource: "@SuluSalesOrderBundle/Resources/config/routing_api.xml"
    prefix: /admin/api

sulu_sales_shipping:
    resource: "@SuluSalesShippingBundle/Resources/config/routing.xml"
    prefix: /admin/shipping

sulu_sales_shipping_api:
    type: rest
    resource: "@SuluSalesShippingBundle/Resources/config/routing_api.xml"
    prefix: /admin/api
